version: "3.3"

services:
  instant-ngp:
    image: containers.rc.northeastern.edu/rc/instantngp:1.3
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    stdin_open: true
    tty: true
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics
      DISPLAY: $DISPLAY
    volumes:
      - ../:/volume
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /volume
    command: /bin/bash
    deploy:
    

